[upload]
  [upload.pws]
  file_or_dir_name = "Master_Passworlds.kdbx"
  file_or_dir_path = "/home/dev/Desktop/Master_Passworlds.kdbx"
  veracrypt_mount_dir = "/home/dev/Downloads/master-pws"
  veracrypt_file_name = "master-pws"
  veracrypt_volume_pw = "Marios96<#>"
  upload_to_clouds = [ "dg", "od_rcl" ]
  upload_to_cloud_dir = "desk"
  veracrypt_user_pw = "1144"
#   [upload.txt]
# #   Add the name of the file or dir
#   file_or_dir_name = "Text File (4).txt"
# #   Add the dir or the file you want to upload
#   file_or_dir_path = "/home/dev/Desktop/Text File (4).txt"
# #   based on cloud_providers section bellow add one or more cloud_name 's
#   upload_to_clouds = [ "dge", "ode_rcl" ]
# #   cloud dir to upload to
#   upload_to_cloud_dir = "OBvault"
# #   optional Veracrypt container
#   # veracrypt_mount_dir = "/home/dev/Downloads/text-master"
#   # veracrypt_file_name = "text-master"
#   # veracrypt_volume_pw = "Marios96<#>"
# veracrypt_user_pw = "1144"
  [upload.obsidian]
#   Add the name of the file or dir
  file_or_dir_name = "OBvault"
#   Add the dir or the file you want to upload
  file_or_dir_path = "/home/dev/Documents/OBvault/"
#   based on cloud_providers section bellow add one or more cloud_name 's
  upload_to_clouds = [ "dge", "ode_rcl" ]
#   cloud dir to upload to
  upload_to_cloud_dir = "OBvault"
#   optional Veracrypt container
  # veracrypt_mount_dir = "/home/dev/Downloads/text-master"
  # veracrypt_file_name = "text-master"
  # veracrypt_volume_pw = "Marios96<#>"
# veracrypt_user_pw = "1144"

[cache_dir]
# dir = "cache.bin"
dir = "/home/dev/Development/scripts/cloud_sync/cache.bin"


[cloud_providers]
  [cloud_providers.dg]
  cloud_name = "dg"
  dir = "/home/dev/Documents/cloud/dg/"
  paste_to_dir = "dg:files/"

  [cloud_providers.od_rcl]
  cloud_name = "od_rcl"
  dir = "/home/dev/Documents/cloud/od/"
  paste_to_dir = "od_rcl:desk/"

  [cloud_providers.dge]
  cloud_name = "dge"
  dir = "/home/dev/Documents/cloud/dge/"
  paste_to_dir = "dge:desk/"

  [cloud_providers.ode_rcl]
  cloud_name = "ode_rcl"
  dir = "/home/dev/Documents/cloud/ode/"
  paste_to_dir = "ode_rcl:desk/"




